# Generated by Django 3.0.6 on 2020-05-13 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Current_answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a1', models.IntegerField(blank=True, null=True)),
                ('a2', models.IntegerField(blank=True, null=True)),
                ('a3', models.IntegerField(blank=True, null=True)),
                ('a4', models.IntegerField(blank=True, null=True)),
                ('a5', models.IntegerField(blank=True, null=True)),
                ('a6', models.IntegerField(blank=True, null=True)),
                ('a7', models.IntegerField(blank=True, null=True)),
                ('a8', models.IntegerField(blank=True, null=True)),
                ('a9', models.IntegerField(blank=True, null=True)),
                ('a10', models.IntegerField(blank=True, null=True)),
                ('a11', models.IntegerField(blank=True, null=True)),
                ('a12', models.IntegerField(blank=True, null=True)),
                ('a13', models.IntegerField(blank=True, null=True)),
                ('a14', models.IntegerField(blank=True, null=True)),
                ('a15', models.IntegerField(blank=True, null=True)),
                ('a16', models.IntegerField(blank=True, null=True)),
                ('a17', models.IntegerField(blank=True, null=True)),
                ('a18', models.IntegerField(blank=True, null=True)),
                ('a19', models.IntegerField(blank=True, null=True)),
                ('a20', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ChoiceM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('numberOfVotes', models.IntegerField(default=0)),
                ('question_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ankietaapp.QuestionM')),
            ],
        ),
    ]
